str = 'GCCGCTGGAGAGGATCAACATCAATGAAGCTTATGCTTCAAGGCTTCGAGCGGCGGGCCGCCCGTTCTGGGAACTAGCATGTATAAACTGACGTGCCATCTCTTAAGGCAAGTGGAGACTCGCTTGAGACTGTCGAGTCGAGGACCACTCTGACAGATCAGTACCGCCCCATTACGTCCCTCGCGAATGCATCAAATCCTCCCAGCGAACGAAGCTAAATGCGTCTGACAGGAATTCTCAAGGCGGGATCCTTTGAAACTGGTTCGGGTCGTGTTGTATGGTGGTCCCTACATTCTTGGCCAAACGGAAATCTAGGGAAGACCACCGAGAGAGTGGGGTATTTAGCATGCGAAAATGATGTAGACCAAGGTTAGAACGTGCTAATTCTCGTTTTACGATACATAGGGGCATGAGGCGCGGAGCCGTTGTAGGAAAGGATTAGTAGAGTAGACACTGGCAGGATGGCATAGAACTATTCGACAACTAGCAATTGAGCATATGTGATGGTATCGCCCAAAGGGAAGGTAGTGCCCCCCATCCGCCTCCCTCGGAAGCCCACCAGTATTGGCGGATCAACAGACGTGGGTCCACTGCTAGGGGAGCCATGGTCGTGGCTCCGGCACCATTACCTCGGGTCGTAAAAAGGCGCGTCAGCCCTGGGCCAGTATGGCTGATACAAGAGTGTCAAGATAAATTCGGATAACATCCCCGCCGTAGTCGTCCATCCTTTTTCCATGTCCGAGCTTGAGCAGCTCAGATCTAAGTGTATCGATGCGGCACTGAGTGGGCGCCTCGTGGGAGCCGCTCTCAGCACGCGTAGTCGGGAAGAAAAACGTGCCAACTGAGCCACATAAACGGCAGGATTGCTTACGGTGGAGCGGCAGCGTTCCCCACTCTATACACCAGTTCTGGGGAACTACGACCTGTGTGCACCGGCAGGACTGGCCCGCTATTCAATTTGCACAAGATGACAGATTACCGCAAGCCT'

char = list(str)

print char

dict = {}

for word in char:
        #print word;
        if word in dict:
                dict[word] += 1;
        else:
                dict[word] = 1;

print dict['A'],dict['C'],dict['G'],dict['T']

for key, value in dict.items():
        print key, value

